a=int(input("Enter two Number=="))
b=int(input())
print(a ,">" ,b,"==",a>b) 
print(a ,"<" ,b,"==",a<b) 
print(a ,"==" ,b,"==",a==b) 
print(a ,"!=" ,b,"==",a!=b) 
print(a ,">=" ,b,"==",a>=b) 
print(a ,"<=" ,b,"==",a<=b) 